---
version: "0.1.0"

server:
  host: "localhost"
  port: 8030
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  database: "maestro"
  ssl_mode: "disable"
  max_connections: 25
  max_idle_connections: 5

logging:
  level: "info"
  format: "json"
  output: "stdout"

mcp:
  tool_timeout: "15s"
  timeouts:
    health: "30s"
    query: "30s"
    write_single: "900s"
    write_bulk: "3600s"
    delete: "60s"
    cleanup: "60s"
    setup_database: "60s"
    list_documents: "30s"
    count_documents: "15s"
    list_collections: "15s"
    get_collection_info: "30s"

  embedding:
    provider: "openai"
    model: "text-embedding-ada-002"
    vector_size: 1536

  vector_db:
    type: "milvus"
    milvus:
      host: "localhost"
      port: 19530
      username: ""
      password: ""
      database: "default"
    weaviate:
      url: "http://localhost:8080"
      api_key: ""
      timeout: "10s"
